### ISSUE TITLE
Add config file, and aliases for tracked contracts

### ISSUE THREAD

**Issue by thepalbi** [thepalbi/ethereum-prometheus-exporter#8]
Add an alias to contract address I want to listen. For example, when adding `0x128310273012ueaoidu`, add a string alias like `pepito`, that will be shipped as a const label.

As per consensus, in this task a config file will also be added, to use instead of the CLI arguments. Much cleaner!

**Pending**
- [x] Add a config file instead of CLI arguments https://github.com/thepalbi/ethereum-prometheus-exporter/pull/13
- [x] Add aliases for ERC20 tracked contracts

**Comment by leandro-deveikis** [comment]
I thinks this is resolved with PR #20 right? @thepalbi
